### PR TITLE
First draft of new LE interface. The str comparison for the different state does not work yet.

### PR DESCRIPTION
**Pull request by bindgens1**
This is just a rough idea. As mentioned above the string comparison does not work yet:

str(_lees_edwards_protocol[0]) == "stepstrain" and  len(_lees_edwards_protocol) == 2

### CODE REVIEW

**Comment by pdebuyl** [comment]
Hi Sebastian,

I have a few comments already :-)

1. It is best to avoid committing commented code. (hpp file here with the typedef)
2. Currently, the struct is not defined and setting the properties is done on `lees_edwards_function` instead of `lees_edwards_protocol.lees_edwards_function` and there is a mismatch.

```
File "clean_poly_le.py", line 109, in <module>
    system.lees_edwards_protocol = 'steady_shear'
TypeError: Argument '_lees_edwards_protocol' has incorrect type (expected list, got str)
```

What I think should be set by the lees edwards properties is what you have already "protocol", "offset", ..., and also the time at which the protocol is started so that the time for either the "position offset" or for the oscillatory time is "time - less_edwards_start_time" where "time" is the global one.

Also, you can start by not storing function pointers here and have one lees_edwards routine in the integration loop that will select the appropriate protocol. This is easier to write, to debug, and should not pose any performance issue (it is all at the C++ level and has complexity "O(1)").

**Comment by pdebuyl** [comment]
And I suggest to store the protocol in an enum: https://en.wikipedia.org/wiki/Enumerated_type#C++

This way, apart from the "setting" stage at the Python call, there is only an integer-level comparison.

**Comment by pdebuyl** [comment]
And I suggest to store the protocol in an enum: https://en.wikipedia.org/wiki/Enumerated_type#C++

This way, apart from the "setting" stage at the Python call, there is only an integer-level comparison.

**Comment by bindgens1** [comment]
I thought of setting the protocol like: 

```
system.lees_edwards_protocol = ['steady_shear', 0.1]
system.lees_edwards_protocol = ['oscillatory_shear', 0.1, 0.5]
```

We should also think of introducing a sampling frequency for the stress calculation etc. 

As I mentioned: it's just a suggestion.

**Pull request closed without merging**
